server.port=8080

# Cấu hình JWT & Header
authToken.header=Authorization
jwt.secret=9a4f2c8d7e1b5a3f6c8d0e2b4a6c8e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7f9a1b3c5d7e9f1a3b5c7d9e1f3a5b
jwt.expiration=86400

# Cấu hình tạm Database H2 (nếu chưa muốn bật MySQL ngay để test)
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

# Cấu hình MySQL (khi bạn sẵn sàng kết nối DB)
spring.datasource.url=jdbc:mysql://localhost:3306/b2c_store?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Bật log chi tiết Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Thông số cấu hình máy chủ Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chuonglehoai1210@gmail.com
spring.mail.password=gqgb fzzr fhkm vhlq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true